### ISSUE TITLE
Only sweeping small amounts

### ISSUE THREAD

**Issue by nelsonpk** [Jpja/Sweep-XCP-Paperwallet#1]
I've tried twice to sweep my SJCX from 1AgXMqS96dD1LCdaW1F7LsKmtEF1t6eoKe (paper wallet)
The first time, I tried MAX and the second time, the actual balance, but the transactions that I got were:
14	473,239	2 hours ago	SJCX	-0.00000010	17HWh3rtCTNFyLcpb4a5Bvo9HPCQYdaZUp
13	473,207	6 hours ago	SJCX	-0.00000009	17HWh3rtCTNFyLcpb4a5Bvo9HPCQYdaZUp

Any clues or am I going wrong somewhere?
Many thanks
Philip

**Comment by nelsonpk** [comment]
Just tried another avenue - sweeping from paper wallet back to Counterwallet - even less successful - transaction went through, but nothing at all transferred.

**Comment by Jpja** [comment]
integer overflow in max amount. fixed.
